### ISSUE TITLE
Crashes on the same app

### ISSUE THREAD

**Issue by wbroek** [Touchwonders/testflight-exporter#2]
When downloading one app (others works) it crashes with this stack:

```
/Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:227:in `process_install_page': undefined method `text' for nil:NilClass (NoMethodError)
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:222:in `block in process_build_page'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:442:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:222:in `process_build_page'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:215:in `block (2 levels) in process_builds_page'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:442:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:211:in `block in process_builds_page'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:210:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:210:in `process_builds_page'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:180:in `block (2 levels) in process_dashboard_page'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:442:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:161:in `block in process_dashboard_page'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:156:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:156:in `process_dashboard_page'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:112:in `block in process_teams'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:110:in `each'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:110:in `process_teams'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:85:in `block (3 levels) in process_login_page'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.6.21/lib/highline/menu.rb:312:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.6.21/lib/highline/menu.rb:312:in `select'
    from /Library/Ruby/Gems/2.0.0/gems/highline-1.6.21/lib/highline.rb:362:in `choose'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:76:in `block in process_login_page'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:442:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:54:in `process_login_page'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:36:in `block in setup'
    from /Library/Ruby/Gems/2.0.0/gems/mechanize-2.7.3/lib/mechanize.rb:442:in `get'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/lib/testflight_exporter.rb:36:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/bin/tfexporter:30:in `block (2 levels) in run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:179:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/command.rb:154:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:421:in `run_active_command'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/runner.rb:81:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.0/lib/commander/delegates.rb:15:in `run!'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/bin/tfexporter:36:in `run'
    from /Library/Ruby/Gems/2.0.0/gems/TestFlightExporter-0.0.2/bin/tfexporter:40:in `<top (required)>'
    from /usr/bin/tfexporter:23:in `load'
    from /usr/bin/tfexporter:23:in `<main>'
```

**Comment by fabiomassimo** [comment]
It seems to concern the parsing of the release note. 
Do you recognize any "unusual" character or none release note for the build it is trying to download? (if it happens immediately I assume it is regarding the latest build)

**Comment by fabiomassimo** [comment]
I improved release note parsing and published a new version (0.0.3).

This dd0b77afb1846d6226fdc2327290d0a45f0cc2cc should solve your issue.

**Comment by wbroek** [comment]
It works now... kinda it now says there isn;t a ipa to download:
WARN [2015-02-20 22:22:59.26]: No IPA link found. Do you have permission for current application?

There was before

**Comment by fabiomassimo** [comment]
Could you check if you have granted permissions for the build you're trying to download?
Usually this error is caused by missing permissions.

**Comment by wbroek** [comment]
Ah yes, checked the permission and indeed it was not right. Thx
